'use client';

import { motion } from 'framer-motion';
import { FileText, AlertTriangle, Gavel } from 'lucide-react';
import { Card } from '@/components/ui';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="space-y-8"
      >
        {/* Header */}
        <div className="text-center space-y-4">
          <FileText size={48} className="text-bullish mx-auto" />
          <h1 className="text-4xl font-extrabold text-text-primary">Terms of Service</h1>
          <p className="text-text-secondary">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        {/* Content */}
        <Card padding="lg" className="space-y-6">
          <section>
            <h2 className="text-2xl font-bold text-text-primary mb-3">1. Acceptance of Terms</h2>
            <p className="text-text-secondary leading-relaxed">
              By accessing and using PulseForge, you accept and agree to be bound by the terms 
              and provision of this agreement. If you do not agree to abide by the above, please 
              do not use this service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary mb-3">2. Use License</h2>
            <p className="text-text-secondary leading-relaxed mb-3">
              Permission is granted to temporarily use PulseForge for personal, non-commercial 
              research purposes only. This is the grant of a license, not a transfer of title, and under this license you may not:
            </p>
            <ul className="list-disc list-inside space-y-2 text-text-secondary ml-4">
              <li>Modify or copy the materials</li>
              <li>Use the materials for any commercial purpose</li>
              <li>Attempt to decompile or reverse engineer any software</li>
              <li>Remove any copyright or other proprietary notations from the materials</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary mb-3 flex items-center gap-2">
              <AlertTriangle size={20} className="text-warning" />
              3. Disclaimer
            </h2>
            <p className="text-text-secondary leading-relaxed mb-3">
              <strong className="text-text-primary">IMPORTANT:</strong> PulseForge is a demo research tool and is not financial advice. 
              This is an experimental analysis platform. The materials on PulseForge are provided on an 'as is' basis. 
              PulseForge makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, 
              without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or 
              non-infringement of intellectual property or other violation of rights.
            </p>
            <p className="text-text-secondary leading-relaxed">
              All predictions, analysis, and insights generated by PulseForge are based on market data and AI analysis which may be inaccurate. 
              Do not make financial decisions based solely on this tool. Always conduct your own research and consult with financial professionals.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary mb-3">4. Limitations</h2>
            <p className="text-text-secondary leading-relaxed mb-3">
              In no event shall PulseForge or its suppliers be liable for any damages (including, without limitation, 
              damages for loss of data or profit, or due to business interruption) arising out of the use or inability 
              to use PulseForge, even if PulseForge or a PulseForge authorized representative has been notified orally 
              or in writing of the possibility of such damage.
            </p>
            <p className="text-text-secondary leading-relaxed">
              Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for 
              consequential or incidental damages, these limitations may not apply to you.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary mb-3">5. Data and Content</h2>
            <p className="text-text-secondary leading-relaxed">
              PulseForge uses live data from Polymarket's public APIs. We make no guarantees about the accuracy, 
              completeness, or timeliness of this data. All market data is provided by third parties and we are not 
              responsible for any errors or omissions in the data.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary mb-3">6. User Conduct</h2>
            <p className="text-text-secondary leading-relaxed mb-3">
              You agree not to:
            </p>
            <ul className="list-disc list-inside space-y-2 text-text-secondary ml-4">
              <li>Use PulseForge for any illegal or unauthorized purpose</li>
              <li>Attempt to gain unauthorized access to any part of the service</li>
              <li>Interfere with or disrupt the service or servers</li>
              <li>Use automated systems to access the service without permission</li>
              <li>Reproduce, duplicate, or copy any part of PulseForge without permission</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary mb-3">7. Modifications</h2>
            <p className="text-text-secondary leading-relaxed">
              PulseForge may revise these terms of service at any time without notice. By using this service, 
              you are agreeing to be bound by the then current version of these terms of service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary mb-3 flex items-center gap-2">
              <Gavel size={20} />
              8. Governing Law
            </h2>
            <p className="text-text-secondary leading-relaxed">
              These terms and conditions are governed by and construed in accordance with applicable laws. 
              Any disputes relating to these terms shall be subject to the exclusive jurisdiction of the courts 
              of the jurisdiction where PulseForge is operated.
            </p>
          </section>
        </Card>

        {/* Back to Home */}
        <div className="flex justify-center pt-4">
          <Link 
            href="/"
            className="text-bullish hover:underline font-medium text-sm"
          >
            ← Back to Home
          </Link>
        </div>
      </motion.div>
    </div>
  );
}
